#!/bin/sh

# Copy the biglinux icon file to all recursive folders within ../places/*
find /usr/share/icons/bloom/places -type f -name deepin-launcher.svg -exec cp -f /usr/share/icons/bloom/places/big-deepin-launcher.svg {} \;
