#!/bin/sh

PATH_WALLPAPER="/usr/share/wallpapers"

# Move all wallpapers from biglinux into the deepin folder
if [ -e "$PATH_WALLPAPER/deepin" ]; then
    mv $PATH_WALLPAPER/*.jpg $PATH_WALLPAPER/deepin/
    
    # Rename the desktop.jpg file to dde-desktop.jpg and the big-desktop.jpg file to desktop.jpg
    mv $PATH_WALLPAPER/deepin/desktop.jpg $PATH_WALLPAPER/deepin/dde-desktop.jpg
    mv $PATH_WALLPAPER/deepin/big-desktop.jpg $PATH_WALLPAPER/deepin/desktop.jpg
else
    mkdir $PATH_WALLPAPER/deepin
    if [ "$?" -eq "0" ]; then
        mv $PATH_WALLPAPER/*.jpg $PATH_WALLPAPER/deepin/
        
        # Rename the desktop.jpg file to dde-desktop.jpg and the big-desktop.jpg file to desktop.jpg
        mv $PATH_WALLPAPER/deepin/desktop.jpg $PATH_WALLPAPER/deepin/dde-desktop.jpg
        mv $PATH_WALLPAPER/deepin/big-desktop.jpg $PATH_WALLPAPER/deepin/desktop.jpg
    else
        exit 0
    fi
fi
