// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.download.autohideButton", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://www.biglinux.com.br\",\"label\":\"BigLinux\"},null,null,{\"url\":\"https://www.instagram.com\",\"label\":\"Instagram\"},{\"url\":\"https://www.wikipedia.org/\",\"label\":\"wikipedia\"},{\"url\":\"https://twitter.com/\",\"label\":\"twitter\"},{\"url\":\"https://mail.google.com\",\"label\":\"Gmail\"},{\"url\":\"http://outlook.live.com\",\"label\":\"Outlook\"},{\"url\":\"http://maps.google.com\",\"label\":\"Maps\"}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.sessionstore.warnOnQuit", true);
user_pref("browser.startup.homepage_override.mstone", "90.0");
user_pref("browser.startup.page", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"urlbar-container\",\"zoom-controls\",\"save-to-pocket-button\",\"downloads-button\",\"bookmarks-menu-button\",\"fxa-toolbar-menu-button\",\"_9a41dee2-b924-4161-a971-7fb35c053a4a_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"save-to-pocket-button\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\",\"_9a41dee2-b924-4161-a971-7fb35c053a4a_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":10}");
user_pref("browser.tabs.inTitlebar", 1);
user_pref("media.eme.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("general.smoothScroll.lines.durationMaxMS", 125);
user_pref("general.smoothScroll.lines.durationMinMS", 125);
user_pref("general.smoothScroll.mouseWheel.durationMaxMS", 200);
user_pref("general.smoothScroll.mouseWheel.durationMinMS", 100);
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("general.smoothScroll.other.durationMaxMS", 125);
user_pref("general.smoothScroll.other.durationMinMS", 125);
user_pref("general.smoothScroll.pages.durationMaxMS", 125);
user_pref("general.smoothScroll.pages.durationMinMS", 125);
user_pref("mousewheel.min_line_scroll_amount", 30);
user_pref("mousewheel.system_scroll_override_on_root_content.enabled", true);
user_pref("mousewheel.system_scroll_override_on_root_content.horizontal.factor", 175);
user_pref("mousewheel.system_scroll_override_on_root_content.vertical.factor", 175);
user_pref("toolkit.scrollbox.horizontalScrollDistance", 6);
user_pref("toolkit.scrollbox.verticalScrollDistance", 2);
user_pref("browser.startup.upgradeDialog.version", 89);
user_pref("font.name.monospace.x-western", "monospace");
user_pref("font.name.sans-serif.x-western", "Liberation Sans");
user_pref("font.name.serif.x-western", "Liberation Serif");
